// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfxZJV_-kTYpdbLp-ZGnLaItD_L2kn5a4',
    appId: '1:114233698117:web:9c37c9b40af9ab0cfec02c',
    messagingSenderId: '114233698117',
    projectId: 'mygardengnome-16d3b',
    authDomain: 'mygardengnome-16d3b.firebaseapp.com',
    storageBucket: 'mygardengnome-16d3b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtd52QEBqtkNPLFsjRUrfSjxe5WKRPdW8',
    appId: '1:114233698117:android:eceb0aad8eb5f8befec02c',
    messagingSenderId: '114233698117',
    projectId: 'mygardengnome-16d3b',
    storageBucket: 'mygardengnome-16d3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA04bvLkx6PA2pTq8UU51oL7RvdPr8ZRdQ',
    appId: '1:114233698117:ios:341e912df0e38aa0fec02c',
    messagingSenderId: '114233698117',
    projectId: 'mygardengnome-16d3b',
    storageBucket: 'mygardengnome-16d3b.firebasestorage.app',
    iosBundleId: 'com.example.mygardengnome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA04bvLkx6PA2pTq8UU51oL7RvdPr8ZRdQ',
    appId: '1:114233698117:ios:341e912df0e38aa0fec02c',
    messagingSenderId: '114233698117',
    projectId: 'mygardengnome-16d3b',
    storageBucket: 'mygardengnome-16d3b.firebasestorage.app',
    iosBundleId: 'com.example.mygardengnome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfxZJV_-kTYpdbLp-ZGnLaItD_L2kn5a4',
    appId: '1:114233698117:web:a9abf637e1b795e6fec02c',
    messagingSenderId: '114233698117',
    projectId: 'mygardengnome-16d3b',
    authDomain: 'mygardengnome-16d3b.firebaseapp.com',
    storageBucket: 'mygardengnome-16d3b.firebasestorage.app',
  );
}
